### PR TITLE
Fix: Fixed bug where Lu Ban could not identify the machine model

### PR DESCRIPTION
**Pull request by xhycode**

### CODE REVIEW

**Review by scotthsl — APPROVED** [review]

**Comment by scyto** [comment]
@scotthsl this fixed the issue when connecting to serial ports, it has not fixed the same issue over wifi.

**Comment by scotthsl** [comment]
@scyto Thanks for your feedback!
We are also aware that this problem has not been completely fixed(contains scenarios that connecting to serial ports). So the recently released firmware RELEASE NOTE does not state that this bug is fixed. 
Will fixed issue as soon as possible!

**Comment by scyto** [comment]
@scotthsl thanks for letting me know, i never assume that release notes have all the bugs fixed listed in them :-)
I came to the wrong conclusion because this title of this commit is too broad (it should say scenarios it did fix)

So I saw it in the release diff and just assumed :-)

image

**Comment by scotthsl** [comment]
Hi @scyto ，
    Sorry for late reply, The feedback from the test engineers is that the latest version of firmware is able to recognize the machine properly if luban is connected directly to the machine via Wi-Fi. At this time luban is getting the model information directly from the screen, so the screen needs to be able to recognize the currently connected model properly first. Could you please provide the version of Luban  you are using and the firmware version of the machine?

**Pull request merged**
